networks:
    default:
        external: true
        name: dev

services:
    withbloo-ui:
        image: nginx:alpine
        container_name: withbloo-ui
        environment:
            - VIRTUAL_HOST=app.withbloo.home
        volumes:
            - ./ui/docker/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./ui/dist:/usr/share/nginx/html:ro

    withbloo-ui-npm:
        image: node:20-alpine
        container_name: withbloo-ui-npm
        command: "npm run dev"
        volumes:
            - ./ui:/home/node/app
        working_dir: /home/node/app
